name: Playwright Tests on PR or Push
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
        working-directory: ./mineral-collection-site
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./mineral-collection-site
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./mineral-collection-site
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: mineral-collection-site/playwright-report/
          retention-days: 30
