name: Playwright Tests on Vercel Deployment Success
on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'
jobs:
  run-e2es:
    if: github.event_name == 'repository_dispatch'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}
      - name: Install dependencies
        run: npm ci
        working-directory: ./mineral-collection-site
      - name: Install playwright
        run: npx playwright install --with-deps
        working-directory: ./mineral-collection-site
      - name: Run tests
        run: npm run playwright
        working-directory: ./mineral-collection-site
        env:
          BASE_URL: ${{ github.event.client_payload.url }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: mineral-collection-site/playwright-report/
          retention-days: 30
